#define W "\x01\x00\x00\x80"
#define O "\x00\x00\x00\x00"
#define NORTH_OR_SOUTH W W W W W W W W W W W W W W W W
#define CENTER W O O O O O O O O O O O O O O W
#define SQUARE_EDGE_ROW_2 W O O O W W W W W W W W O O O W
#define SQUARE_SIDE_ROW_2 W O O O W O O O O O O W O O O W
#define EMPTY O O O O O O O O O O O O O O O O
#define FLOOR \
  NORTH_OR_SOUTH NORTH_OR_SOUTH NORTH_OR_SOUTH NORTH_OR_SOUTH \
  NORTH_OR_SOUTH NORTH_OR_SOUTH NORTH_OR_SOUTH NORTH_OR_SOUTH \
  NORTH_OR_SOUTH NORTH_OR_SOUTH NORTH_OR_SOUTH NORTH_OR_SOUTH \
  NORTH_OR_SOUTH NORTH_OR_SOUTH NORTH_OR_SOUTH NORTH_OR_SOUTH
#define WALLS_LOWER \
  NORTH_OR_SOUTH \
  CENTER CENTER CENTER \
  SQUARE_EDGE_ROW_2 \
  SQUARE_SIDE_ROW_2 SQUARE_SIDE_ROW_2 SQUARE_SIDE_ROW_2 \
  SQUARE_SIDE_ROW_2 SQUARE_SIDE_ROW_2 SQUARE_SIDE_ROW_2 \
  SQUARE_EDGE_ROW_2 \
  CENTER CENTER CENTER \
  NORTH_OR_SOUTH
#define WALLS_UPPER \
  NORTH_OR_SOUTH \
  CENTER CENTER CENTER \
  CENTER CENTER CENTER \
  CENTER CENTER CENTER \
  CENTER CENTER CENTER \
  CENTER CENTER \
  NORTH_OR_SOUTH
#define EMPTY_Z \
  EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY \
  EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY EMPTY
#define A_CHUNK \
  WALLS_LOWER
